### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kuradi** [pilotak/homeassistant-mikrotik#2]
guidelines are:

`To enable MikroTik platform in your installation, add the following to your configuration.yaml file:

# Example configuration.yaml entry
mikrotik:
  host: !secret router_host
  username: !secret router_user
  password: !secret router_pass`

official mikrotik guidelines are (https://www.home-assistant.io/integrations/mikrotik/)

`# Example configuration.yaml entry
mikrotik:
  - host: IP_ADDRESS
    username: ROUTEROS_USERNAME
    password: ROUTEROS_PASSWORD`

as you see they are slightly different. "-host" vs "host".
which is correct?

**Comment by pilotak** [comment]
Hi sorry i spotted the issue now. This is not and official mikrotik component, maybe i should rename it to make it more clearer
