### ISSUE TITLE
sending sms with mikrotik

### ISSUE THREAD

**Issue by KM192** [pilotak/homeassistant-mikrotik#4]
Is it possible to send sms with mikrotik.api ?
Should I use find for that becouse command does not have parameters ?

e.g.
command: /tool sms send  
command_params: message="Test" phone-number=XXXXXXXXXXX channel=0 port=usb2

**Comment by pilotak** [comment]
I have not tried...

Unfortunatelly `command` doesn't support parameters and i don't think that `find` will work, but you can try. In order for `command` to accept parameters, there need to be work done. Either you can try and then submit PR or i can but not in near future

**Comment by KM192** [comment]
I already try to put it entirly into command or find with parameters and doesn't work :(
Use case - use mikrotik sms LTE modem capability to notify about lack of internet access or power downtime.

**Comment by KM192** [comment]
btw - don't you have already CONF_PARAMS in your code? almost ready ?

**Comment by pilotak** [comment]
almost...

**Comment by KM192** [comment]
Afer adding 'params' to mikrotik.api service actually it's working on current code:

command: /tool sms send
params: phone-number="XXXXXXXXXXX" channel=0 port=usb2 message="Test"

**Comment by pilotak** [comment]
perfect, could you please submit PR?

**Comment by KM192** [comment]
#5 just services definition changed

**Comment by pilotak** [comment]
@KM192 I have pushed new changes, could you please test it? *(clone from git, it's not available from HACS yet)*

**Comment by pilotak** [comment]
you can now send SMS with spaces, which was not available before due to parsing parameters error

```yaml
command: /tool sms send
params: message="Test with spaces" phone-number="XXXXXXXXXXX" channel=0 port="usb2"
```
