### ISSUE TITLE
INtegration not working

### ISSUE THREAD

**Issue by audiobah** [pilotak/homeassistant-mikrotik#6]
Hi,  integration installed via HACS, but i am getting this error.

Logger: homeassistant.config_entries
Source: config_entries.py:563
First occurred: 18:20:14 (1 occurrences)
Last logged: 18:20:14

Error occurred loading configuration flow for integration vlc_telnet: No module named 'homeassistant.components.vlc_telnet.config_flow'

**Comment by audiobah** [comment]
And this also

Logger: homeassistant.setup
Source: custom_components/mikrotik/__init__.py:58
First occurred: 18:19:50 (1 occurrences)
Last logged: 18:19:50

Error during setup of component mikrotik
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/mikrotik/__init__.py", line 58, in async_setup
    conf = config[DOMAIN]
KeyError: 'mikrotik'

**Comment by pilotak** [comment]
The first one has nothing to do with this component as the log says: `homeassistant.components.vlc_telnet.config_flow`

Maybe after you fix it, the error for mikrotik disappears?

**Comment by pilotak** [comment]
Also it's not possible to install this component via HACS, only https://github.com/tomaae/homeassistant-mikrotik_router which is not this one
